### ISSUE TITLE
Контейнер

### ISSUE THREAD

**Issue by aaccent-seva** [aaccent/bikini_layout#3]
Для расширений выше `1920px` надо вычислять контейнер и отступы динамически:
```css
.site-container {
    /** Насколько процентов изменился экран относительно ширины из макета */
    --screen-diff: calc((100vw - 1680px) / (1680 / 100) / 100);

    --container-width: calc(1680px + 1680px * var(--screen-diff));
    max-width: var(--container-width);

    --container-padding: calc(60px + 60px * var(--screen-diff));
    padding: 0 var(--container-padding);
}
```
